server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: false
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:smucode-auth-service}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8000/api/auth/.well-known/jwks.json}

eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

logging:
  level:
    root: INFO
    com.cs203.smucode: DEBUG
